### ISSUE TITLE
E01F04US09 - Eu, como Jogador, desejo visualizar gráficos relacionados aos meus treinos para analisar meu resultado de forma mais concisa

### ISSUE THREAD

**Issue by Ronyell** [Gibb-Launcher/GibbLauncher-App#14]
Tasks:

- [x] Criar gráfico com a porcentagem de jogadas feitas
- [x] Criar gráfico de dentro/fora por posição de lançamento(esquerda, direita, meio)
- [x] Criar gráfico por tipo de jogada rebatidas (porcentagem de dentro/fora)
- [x] Criar gráfico com as **skills** do usuário com base nas rebatidas corretas
- [x] Permitir que o usuário selecione data de início/fim da análise

**Comment by joaopaulonsoares** [comment]
Falta inserir os Dados Reais
